In [2]:
import pandas as pd

df = pd.read_csv("online_retail_II.csv")

df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

In [3]:
df = pd.read_csv("/Users/kotori/GMS_AFKMC2/data/rfm_customers.csv")
df.head()

,customer_id,R,F,M,F_log1p,M_log1p,R_z,F_z,M_z
0,12346.0,325,12,77556.46,2.564949,11.258774,0.595584,1.254496,3.186625
1,12347.0,1,8,5633.32,2.197225,8.636632,-0.952279,0.800166,1.297127
2,12348.0,74,5,2019.40,1.791759,7.611051,-0.603532,0.299207,0.558100
3,12349.0,18,4,4428.69,1.609438,8.396085,-0.871064,0.073946,1.123790
4,12350.0,309,1,334.40,0.693147,5.815324,0.519146,-1.058146,-0.735888

In [6]:
# print R_z, F_z, M_z
df[["customer_id", "R_z", "F_z", "M_z"]].head()
# print R_z, F_z, M_z
df[["customer_id", "R_z", "F_z", "M_z"]].head()
# print R_z, F_z, M_z
df[["customer_id", "R_z", "F_z", "M_z"]].head()

   customer_id       R_z       F_z       M_z
0      12346.0  0.595584  1.254496  3.186625
1      12347.0 -0.952279  0.800166  1.297127
2      12348.0 -0.603532  0.299207  0.558100
3      12349.0 -0.871064  0.073946  1.123790
4      12350.0  0.519146 -1.058146 -0.735888